### ISSUE TITLE
모바일 - 체크박스 본문 텍스트와 간격 수정 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#12]
<img width="319" alt="스크린샷 2021-07-18 오후 5 19 56" src="https://user-images.githubusercontent.com/71932058/126060657-ed728ebc-b136-4e20-95fe-d0ba844a46ea.png">

- 체크박스 16px 유지 
- 앞쪽 간격 18px / 본문 텍스트와 간격 13px 로 수정 
- 터치영역 60*50 (h*w) 로 좀 더 넓게 수정

**Comment by chichchic** [comment]
https://github.com/chichchic/task_struct/commit/17989e5fd0b0a812f26a16957fe8d35001933c77
