### ISSUE TITLE
모바일 / 캘린더에 done 표시 dot 미노출 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#28]
계정: j.jisook@gmail.com 

26일 완료한 목록이 있고, 하단 목록에도 done이 표시되는데 
캘린더 26일에는 dot 표시가 없습니다. 

![IMG_0902](https://user-images.githubusercontent.com/71932058/127149424-9edb48e4-35f6-4557-9bc8-6a33b34ff108.jpg)
![IMG_0901](https://user-images.githubusercontent.com/71932058/127149434-ce152b4e-295b-4310-8466-d8975ebf6362.jpg)

**Comment by chichchic** [comment]
모바일 캘린더에도 dot 기능이 있는걸까요?

**Comment by jisook325** [comment]
@chichchic 앗 제가.. 피그마에 빼먹었는데 동일한 기능으로 생각했어요 ㅠㅠ 혹시 기능 추가가 어렵다면 말씀해주세요! 모바일에서는 스킵하고 가야할 것 같습니다.

**Comment by chichchic** [comment]
어려운건 아니라 모바일에도 그럼 동일하게 추가해두도록 할게요!!
