### ISSUE TITLE
모바일 / 우선순위 입력화면 수정 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#29]
![image](https://user-images.githubusercontent.com/71932058/127149523-4440371e-d2b2-4d66-afff-61fd79cff06e.png)

https://www.figma.com/file/rancshye84GaW5wuShlHF5/to-do-%EC%B4%88%EC%95%88?node-id=53%3A457

해당 버전으로 모바일 우선순위 선택 뷰 수정 부탁드립니다. 

1. 텍스트 내용 및 정렬 변경 
2. 텍스트 각 줄 별 폰트 크기와 볼드 설정이 다릅니다. 꼭 유의해주세요! 
3. 탭 영역은 피그마에 표시한 것처럼 여유롭게 잡아주세요 (칩 + 하단 텍스트 모두 탭 영역으로 잡음)

**Comment by chichchic** [comment]
텍스트 내용은 다국어 지원으로 되어 있는 해당 부분 매칭이 어떻게 변경된걸까요.
