### ISSUE TITLE
PC / 추가하기 위치 변경 (상단 바 고정에서 리스트 내로)

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#31]
<img width="651" alt="스크린샷 2021-07-27 오후 9 08 58" src="https://user-images.githubusercontent.com/71932058/127151070-4409eb02-ebd5-4770-8a3a-a08121488bae.png">

PC 추가하기 버튼 위치를 to do list 내로 변경할 수 있을까요? 

버튼 크기 250px 로 늘려서 강조하기 

**위치 후보** 
**1. 마지막 list 항목과 10px 여유 간격 두고 고정 (위 이미지 참고)**
   -  할 일 수에 따라 위치가 바뀜
   -  캘린더 높이보다 할 일이 많은 경우 하단 높이에 붙어서 고정되고 안쪽 리스트만 스크롤 
<img width="764" alt="스크린샷 2021-07-27 오후 9 15 03" src="https://user-images.githubusercontent.com/71932058/127151877-f94c635b-d70c-41de-aeaf-508829b080d4.png">

**2. 캘린더 가장 하단 높이에 고정 (이미지 참고)** 
<img width="654" alt="스크린샷 2021-07-27 오후 9 10 54" src="https://user-images.githubusercontent.com/71932058/127151325-455f944d-0efd-4f43-8789-07b528731823.png">

pc 위치를 중간으로 바꿔봤는데,, 
보시고 의견 주세요! 
(2번처럼 고정하는게 좋을 것 같긴 하네요)

**Comment by chichchic** [comment]
저는 모바일이랑 동일하게 2번 형식으로 가는게 조금 더 좋아보이긴 하네요

**Comment by jisook325** [comment]
@chichchic 네 그러면 피그마 2번 형태로 고정해두겠습니다! 슬랙 공유 한번 더 드릴게요~
