### ISSUE TITLE
수정하기 아이콘 변경 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#35]
https://materialdesignicons.com/icon/pencil-outline

이모티콘 아니구 해당 아이콘으로 변경 부탁드려요! 

36 픽셀로 해주시면 될 것 같습니다. 

![IMG_D6A2C79C0B9C-1](https://user-images.githubusercontent.com/71932058/127506311-18215441-c96c-4460-8cfa-f76f2cefb0e4.jpeg)

**Comment by chichchic** [comment]
2bf514f00235a6047d31cbe48d804289e56c323d 에 작업 완료했습니다.
