### ISSUE TITLE
아이콘 크기 확인 요청

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#36]
1. 삭제하기 
2. 복원하기 
3. 수정하기 

등록된 태스크 스와이프해서 나오는 메뉴들의 아이콘 크기가 어떻게 설정되어 있나요? 

36*36 으로 맞추고 확인해볼 수 있을까요? 지금은 좀 크게 보여서요! 

추가로 메인 task 텍스트와 우선순위칩의 폰트 크기도 각각 확인 부탁드립니다.

**Comment by chichchic** [comment]
![Screen Shot 2021-07-30 at 9 52 39 AM](https://user-images.githubusercontent.com/44209226/127583602-ed3a50b6-57cf-4793-8e96-47f63562f33f.png)
![Screen Shot 2021-07-30 at 9 52 47 AM](https://user-images.githubusercontent.com/44209226/127583611-57e82733-2f7f-46e9-a1a8-70aefb03af60.png)
기존 크기는 30 * 30이었습니다.
36*36으로 했을때 사진도 함께 첨부합니다.

**Comment by chichchic** [comment]
메인 task라는게 어떤걸 말하는걸까요?

**Comment by jisook325** [comment]
@chichchic 30*30으로 유지하는게 좋겠네요! 확인 감사합니다. 

메인 task 는 to do 입력하는 텍스트입니다. 
<img width="204" alt="스크린샷 2021-08-01 오후 6 11 34" src="https://user-images.githubusercontent.com/71932058/127765710-a0ccd15f-d08f-49e0-8e5b-caa5c687b959.png">

이 이미지의 텍스트들 크기가 궁금해요!

**Comment by chichchic** [comment]
https://github.com/chichchic/task_struct/issues/39
에 30*30로 적용 완료했습니다.
