### ISSUE TITLE
모바일 / done 리스트 복원 시 to do 카운트 싱크 안 맞음 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#38]
![IMG_B2D2471AD2D4-1](https://user-images.githubusercontent.com/71932058/127507294-e778f72f-54df-498c-990c-a589d62e5c70.jpeg)

done 에서 복원 후 화면입니다. 
task가 복원되었으나 남은 할일 카운트는 그대로 0이네요. 

해당 카운트를 to do 뿐만 아니라 복원한 아이들도 포함해줘야 제대로 표시될 것 같아요!

**Comment by chichchic** [comment]
제가 코드를 잘못 써서 todo가 항상 0인 이슈가 있었습니다. ㅎㅎ;;
https://github.com/chichchic/task_struct/issues/18 이슈와 중복되는 이슈고 현재 수정 완료해서 우선 해당 이슈는 close하도록하겠습니다!
