### ISSUE TITLE
모바일 / 캘린더 done 날짜 싱크가 안 맞는 듯? 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#39]
![IMG_63F71954EA41-2](https://user-images.githubusercontent.com/71932058/127507712-48f2bb07-a5a3-44f1-9bd5-ef7be93572fd.jpeg)

![IMG_63F71954EA41-1](https://user-images.githubusercontent.com/71932058/127507729-6b6588d4-f8ba-4f21-ab5b-a5b184233d6a.jpeg)

이게.. 말로 설명하기가 좀 애매한데... 
done에서 오늘 날짜를 선택한 (파란색 참) 상태에서는 목록이 안보이고 
한번 더 눌러서 선택 해제한 것 같은 상태에서 목록이 노출됩니다. 

done 진입 시 기본적으로 오늘 날짜 선택 + 리스트를 노출시켜줘야합니다.

**Comment by chichchic** [comment]
해당 이슈는 오늘 날짜 선택시에는 오늘 날짜의 done만을 보여주고 
아무런 날짜도 선택되어있지 않을경우 모든 done을 보여주도록 설계되어있어서 발생한것 같습니다.
DB를 확인해보니 "추가하는중" 데이터는 26일에 완료한 데이터로 보이며 
29일에는 완료한 데이터가 없는것으로 보입니다.
확인 한번 더 부탁드리겠습니다.
![Screen Shot 2021-07-30 at 10 01 41 AM](https://user-images.githubusercontent.com/44209226/127584154-2dc89e13-782a-4989-8ccf-8d3381c1e461.png)
