### ISSUE TITLE
언어 전환 방식 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#40]
1. 설정에서 다른 언어 탭
2. 설정 화면이 선택한 언어로 바뀌고 선택한 언어 강조색
3. 뒤로 가기 했을 때 언어 변경되어 있음 단, 등록한 to do의 내용이나 언어는 바뀌지 않음

언어 설정 시 작동 방식입니다. 
혹시 구현 상 이슈가 있거나 추가 확인이 필요한 경우 슬랙 주세요! (슬랙 답이 더 빨라요 ㅠㅠ)

**Comment by chichchic** [comment]
이미 적용되어 있는 기능입니다.
