### ISSUE TITLE
PC / text 미입력한 태스크 생성이 가능함 -> 이후 수정/삭제 불가함 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#42]
<img width="675" alt="스크린샷 2021-07-29 오후 11 46 26" src="https://user-images.githubusercontent.com/71932058/127513257-ff24c0ab-8f30-4387-9f46-b5e01a9c401e.png">

pc에서 공란으로 엔터를 누른 경우.. 태스크가 생성됩니다. 
이후 삭제나 수정이 안되네요 ㅠㅠ 

공란으로 등록 시도 시, 토스트에 빨간 테두리를 해주거나 다음 단계로 넘어가지 않도록 막아주세요 ~!!

**Comment by chichchic** [comment]
동일한 에러인것으로 보이는 이슈가 있어 함께 해결하도록 하겠습니다.
![Screen Shot 2021-07-30 at 11 49 38 AM](https://user-images.githubusercontent.com/44209226/127592390-50eaa26b-8a49-44a8-8063-3d0fc58bda4d.png)

**Comment by chichchic** [comment]
> 동일한 에러인것으로 보이는 이슈가 있어 함께 해결하도록 하겠습니다.
> ![Screen Shot 2021-07-30 at 11 49 38 AM](https://user-images.githubusercontent.com/44209226/127592390-50eaa26b-8a49-44a8-8063-3d0fc58bda4d.png)

해당 에러는 다른 에러로 https://github.com/chichchic/task_struct/issues/45 이슈로 옮겼습니다.

**Comment by chichchic** [comment]
재현되지 않아 우선 이슈를 닫도록 하겠습니다.
