### ISSUE TITLE
pc / 문의하기, 공지사항 연결 안 됨 (8.1 저녁) 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#49]
https://task-struct-cbbfb--pr46-feature-issues-g7dtg6q8.web.app/

위에서 확인했습다. 

문의하기 & 공지사항 링크 연결이 안되어있습니다 ~

**Comment by chichchic** [comment]
코드 충돌 일어나서 변경하다 누락시켜 버렸네요... ㅠ

**Comment by chichchic** [comment]
#24, #25 와 중복된 내용이라 닫도록 하겠습니다.
