### ISSUE TITLE
PC / 입력 중 추가하기 버튼이 가릴 경우, 자동 스크롤 적용 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#51]
<img width="695" alt="스크린샷 2021-08-01 오후 9 45 58" src="https://user-images.githubusercontent.com/71932058/127771386-b118c6ee-9698-4cd7-a136-7d5e83cbcc0b.png">
<img width="698" alt="스크린샷 2021-08-01 오후 9 45 55" src="https://user-images.githubusercontent.com/71932058/127771388-92dff5c9-79e9-47f9-b5e2-1c6df66f88ac.png">

연속으로 다양한 태스크를 생성하는 과정에 '추가하기'버튼에 입력창이 가려집니다. 
키보드 입력 또는 우선순위 입력 중에는 해당 태스크 박스(회색 영역?)가 다 보이도록 자동 스크롤 되어야 할 것 같아요.

**Comment by chichchic** [comment]
@jisook325 어떤 내용인지 잘 이해가 가지 않네요
화면에 길게 내용이 적힐수 있도록 하고싶다는걸까요?

**Comment by chichchic** [comment]
재현안됨
