### ISSUE TITLE
PC / task 박스 (회색 영역) 높이 확인 요청 

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#52]
<img width="678" alt="스크린샷 2021-08-01 오후 9 48 07" src="https://user-images.githubusercontent.com/71932058/127771504-156e59e5-27a1-48a4-a7af-d06dab628e7d.png">

해당 박스 크기가 어떻게 되나요!? 
생각보다 높네요.. 좀 더 좁게 해서 한 화면에 많은 태스크를 보여줘도 될 것 같아서요. 

몇 px인지 알려주시면 감사하겠습니다 ㅎㅎ

**Comment by chichchic** [comment]
![Screen Shot 2021-08-01 at 9 52 11 PM](https://user-images.githubusercontent.com/44209226/127771556-ec48924e-5455-47de-802c-1bcc21cddd9b.png)
623 * 88입니다. 테두리 상하 10px 좌18px 우 10px씩 공백(padding) 들어있어서 실제 내부 크기는 595 * 68입니다.
@jisook325
