### ISSUE TITLE
pc / done list에서 미래 날짜 눌렀을 때 무한로딩

### ISSUE THREAD

**Issue by jisook325** [chichchic/task_struct#58]
미래 날짜 탭했을 때
1. 아예 탭을 막거나
2. 탭했을 때 그냥 todo에 유지
as-is: done으로 바뀌고 무한로딩됨

**Comment by chichchic** [comment]
해당 에러는 미래의 날짜를 탭했을 때가 아닌 todo탭에서 날짜를 클릭 해 done으로 이동되면서 생긴 문제로 파악되었습니다.
해당 이슈는  #59 에서 다루고 있습니다.
